spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/subs_dev_db
    username: postgres
    password: 899

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: db/changelog/main-changelog.xml
    url: jdbc:postgresql://localhost:5432/subs_dev_db
    user: postgres
    password: 899
    drop-first: true

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      spring:
        json:
          trusted:
            packages: "*"